global:
  environment: staging
  domain: yas.staging.com
replicas:
  postgresql: 1
  kafka: 1
  zookeeper: 1
  elasticsearch: 1
postgresql:
  host: postgresql.postgres
  username: yasadminuser
  password: admin
elasticsearch:
  username: yas
  password: LarUmB3A49NTg9YmgW4=
redis:
  password: redis
keycloak:
  bootstrapAdmin:
    username: admin
    password: admin
  hostname: identity.yas.staging.com
  backofficeRedirectUrl: http://backoffice.yas.staging.com
  storefrontRedirectUrl: http://storefront.yas.staging.com
applicationConfig:
  spring:
    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: http://identity.yas.test.com/realms/Yas
  springdoc:
    oauthflow:
      authorization-url: http://identity.yas.test.com/realms/Yas/protocol/openid-connect/auth
      token-url: http://identity.yas.test.com/realms/Yas/protocol/openid-connect/token
backofficeBffExtraConfig:
  spring:
    data:
      redis:
        host: redis-master.redis.svc.cluster.local
    security:
      oauth2:
        client:
          provider:
            keycloak:
              issuer-uri: http://identity.yas.test.com/realms/Yas
storefrontBffExtraConfig:
  spring:
    data:
      redis:
        host: redis-master.redis.svc.cluster.local
    security:
      oauth2:
        client:
          provider:
            keycloak:
              issuer-uri: http://identity.yas.test.com/realms/Yas
mediaApplicationConfig:
  yas:
    publicUrl: http://api.yas.staging.com/media
customerApplicationConfig:
  keycloak:
    auth-server-url: http://identity.yas.test.com
searchApplicationConfig:
  elasticsearch:
    url: elasticsearch-es-http.elasticsearch.svc.cluster.local:9200
paymentPaypalApplicationConfig:
  yas:
    public:
      url: http://storefront.yas.staging.com/complete-payment
sampledataApplicationConfig:
  spring:
    datasource:
      product:
        url: jdbc:postgresql://postgresql.postgres.svc.cluster.local:5432/product
      media:
        url: jdbc:postgresql://postgresql.postgres.svc.cluster.local:5432/media
backend:
  replicaCount: 0
  databaseConnectionUrl: jdbc:postgresql://postgresql.postgres.svc.cluster.local:5432
  ingress:
    className: nginx
  service:
    type: ClusterIP
  javaOpts: "-Xmx384m -Xms256m"
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
ui:
  replicaCount: 0
replicaCount: 0
reloader:
  reloader:
    deployment:
      replicas: 0
