apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-dev-tempo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: yas-dev
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: tempo
      targetRevision: 1.24.4
      helm:
        releaseName: tempo
        valueFiles:
          - $values/infrastructure/scripts/observability/tempo.values.yaml
    - repoURL: https://github.com/AkiraTomori/ArgoCD-Advanced.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: yas-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
