config:
  clients:
    - url: http://opentelemetry-collector:3500/loki/api/v1/push
  snippets:
    pipelineStages:
      - docker: {}
    extraRelabelConfigs:
      - action: keep
        source_labels:
          - __meta_kubernetes_namespace
        regex: observability

daemonset:
  enabled: false

deployment:
  enabled: true
  replicaCount: 1