backend:
  image:
    repository: akiratomori/yas-tax
    tag: latest

  nameOverride: tax
  fullnameOverride: tax
  databaseName: tax
  ingress:
    enabled: false
  replicaCount: 1
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
