kafka:
  replicas: 1
zookeeper:
  replicas: 1
  storeSize: 5Gi
postgresql:
  username: yasadminuser
  password: admin
debeziumConnect:
  image: quay.io/strimzi/kafka:0.51.0-kafka-4.1.0
  buildImage: false #Enabled when build debezium-connect-postgresql image