global:
  environment: dev
  domain: yas.dev.com

replicas:
  postgresql: 1
  kafka: 1
  zookeeper: 1
  elasticsearch: 1

postgresql:
  host: postgresql.yas-dev
  username: yasadminuser
  password: admin

elasticsearch:
  username: yas
  password: LarUmB3A49NTg9YmgW4=

redis:
  password: redis

keycloak:
  bootstrapAdmin:
    username: admin
    password: admin
  hostname: identity.yas.dev.com
  backofficeRedirectUrl: http://backoffice.yas.dev.com
  storefrontRedirectUrl: http://storefront.yas.dev.com

applicationConfig:
  spring:
    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: http://identity.yas.dev.com/realms/Yas
  springdoc:
    oauthflow:
      authorization-url: http://identity.yas.dev.com/realms/Yas/protocol/openid-connect/auth
      token-url: http://identity.yas.dev.com/realms/Yas/protocol/openid-connect/token

backofficeBffExtraConfig:
  spring:
    data:
      redis:
        host: redis-master.yas-dev.svc.cluster.local
    security:
      oauth2:
        client:
          provider:
            keycloak:
              issuer-uri: http://identity.yas.dev.com/realms/Yas

storefrontBffExtraConfig:
  spring:
    data:
      redis:
        host: redis-master.yas-dev.svc.cluster.local
    security:
      oauth2:
        client:
          provider:
            keycloak:
              issuer-uri: http://identity.yas.dev.com/realms/Yas

mediaApplicationConfig:
  yas:
    publicUrl: http://api.yas.dev.com/media

customerApplicationConfig:
  keycloak:
    auth-server-url: http://identity.yas.dev.com

searchApplicationConfig:
  elasticsearch:
    url: elasticsearch-es-http.yas-dev.svc.cluster.local:9200

paymentPaypalApplicationConfig:
  yas:
    public:
      url: http://storefront.yas.dev.com/complete-payment

sampledataApplicationConfig:
  spring:
    datasource:
      product:
        url: jdbc:postgresql://postgresql.yas-dev.svc.cluster.local:5432/product
      media:
        url: jdbc:postgresql://postgresql.yas-dev.svc.cluster.local:5432/media

backend:
  replicaCount: 1
  databaseConnectionUrl: jdbc:postgresql://postgresql.yas-dev.svc.cluster.local:5432
  ingress:
    className: nginx
  service:
    type: ClusterIP
  javaOpts: "-Xmx384m -Xms256m"
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"